### ISSUE TITLE
Put each panel into its own shadow dom

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#102]
Panels should be web components. They should be fully insulated, and not have to worry at all about namespacing JS or CSS. Bundle authors should only have to worry about what they're writing, not what everyone else is writing.

As a corollary to this issue, we should consider dropping our dependency on jQuery. The DOM has gotten [pretty good](http://substack.net/weaning_yourself_off_jquery), and bundle authors could still use jquery if they wanted to by putting it in their bower.json. Given the current rate of evolution in the standard JS/HTML specs, jQuery is beginning to feel like a relic of a bygone era.

Overall, my philosophy is that NodeCG itself is a framework of sorts (really it's an application, but it's kind of both). Good frameworks have as few layers of abstraction as possible. We should enable bundle developers to use tools like jQuery if they wish (and many will), but we shouldn't force it on them.

**Comment by Lange** [comment]
Upon further investigation, web component JS is not as insulated as I previously thought. Shadow DOMs share the root's global scope.

This presents a challenge for allowing panels to safely rely on things like jQuery. Are iframes a better solution?

**Comment by Lange** [comment]
Another problem we face is with style encapsulation. There is no good way for web components to inherit the dashboard's bootstrap styling. WebComponents don't allow external stylesheets, so we'd have to fully inline all of bootstrap for each component, which is unacceptably inefficient.

We're considering using Google's Material design, which was built hand-in-hand with Polymer. More research needed.

**Comment by thesupremecommander** [comment]
I think that in this case, functionality trumps style. Encapsulating panels and allowing them to selectively load styles and scripts is a huge boost to panel usability and is worth any style disruptions that may occur. The current method of loading panels is definitely not ideal and probably should be changed sooner rather than later.

Porting to Polymer and material design may present a challenge. The basic elements like the title bar and the notifications are easily implemented, but the Polymer support for a grid (which we would need for proper dashboard functionality) appears to be Polymer/core-layout-grid, which is not very well documented. In addition, we have to be wary of the Polymer update to 0.8, which is a huge change from 0.5 (API-wise) and is closer to what a 1.0 release will look like. Also, we do have to be wary of forcing usage of Polymer, in the same line of thinking as your thoughts re: jQuery usage above.

Another question is that of how to handle regular HTML/Jade panels when web components are introduced. I feel it's best to move forward with web components as the default option, but if that happens the current style of panels will not easily translate over due to differences between shadow DOM and regular DOM. (For one, jQuery is not fully compatible with shadow DOM without using something like `/deep/`.) Current panels could be completely deprecated and removed, but that makes migration to that version of NodeCG even more difficult as bundle authors will have to learn how to use Polymer (though I suppose that has to occur at some point if NodeCG goes along this path).

As a side note: we finally have the capabilities to properly test web components with the migration to Sauce Labs, so that is one hurdle removed in case we do go down this path.

**Comment by Lange** [comment]
You have a point about functionality trumping style here. However, the style of the dashboard is more than just its looks. I spend a lot of time honing the UI of my panels to be as easy to use as possible for my clients. Having some kind of consistent style framework available is very important to me. As we continue to consider turning panels into WebComponents, that style framework may or may not continue to be Bootstrap.

Bootstrap appears to be completely at-odds with WebComponents. It pre-dates them, and no part of Bootstrap was made to play well with them. I'm not aware of any style frameworks aside from Google's Material design that are meant to work well with components. This might be something we have to make ourselves.

**Comment by thesupremecommander** [comment]
It doesn't seem like Bootstrap is interested in supporting shadow DOM in the foreseeable future (as per twbs/bootstrap#14200), so maintaining usage of Bootstrap would require editing the framework heavily.

I wonder, though - would material design not work as a consistent style framework, given how well documented it is and its implementation in Polymer? (If you're referring to the confusion that might be caused by migrating from Bootstrap to material design, I agree that will be a pain point.)

**Comment by Lange** [comment]
Material does currently seem to be the best (only?) prefab option for creating a consistent style across webcomponents. We should invest the time to further research it and maybe make a proof-of-concept dashboard and panel to see if it holds water.

**Comment by Lange** [comment]
Panels are now iframes in 0.7
