### ISSUE TITLE
Possible replicant regression 0.8.5

### ISSUE THREAD

**Issue by Planks** [nodecg/nodecg#228]
Heya

This code block stopped working as it doesn't see a change event on page load in 0.8.5. It works in 0.8.4.

Is this because https://github.com/nodecg/nodecg/commit/9e39d45 has broken something or does this code exploit a bug that should never have worked to begin with?

```
// Checks if the access token has been set yet or not on page load.
    // If not, gets one, if it has already got one, changes the buttons.
    var accessTokenReplicant = nodecg.Replicant('twitchAccessToken', {persistent: false});
    accessTokenReplicant.on('change', function(newValue, oldValue) {
        if (!newValue) {
            var parameter = getParameterByName('code');
            if(parameter != null && parameter != '') {
                nodecg.sendMessage('twitchLoginForwardCode', parameter);
                console.log("code is " + parameter);
            }

            streamControl_login(true);
        }

        else {streamControl_loginSuccessful();}
});
```

([line 149 onwards](https://github.com/speedcontrol/nodecg-speedcontrol/blob/master/dashboard/StreamControlDashboard.js))

**Comment by Lange** [comment]
Thanks for the report! I'll look into this when I can, but for now you may want to try adding a `defaultValue` to the declaration of this Replicant in the extension(s) where its first declared? That may affect how and when these `change` events are fired on page load and may be a sufficient band-aid for now. I never declare a Replicant without a `defaultValue` (even if its just an empty string, empty array, etc), so that may be why I missed this regression.

Additionally, it's not necessary to specify options such as `persistent` on *every* instantiation of a given Replicant. It's only the first declaration of a given Replicant that needs these options passed in. In this specific bundle, the passage of `persistent: false` in the client-side declaration of the `twitchAccessToken` Replicant does nothing, because that Replicant was already declared in an extension. Extensions always fully execute before the web server is spun up, so it can be safe to assume that an extension will declare its Replicants before any web client could declare theirs.

I realize that this behavior is opaque and not particularly intuitive, and it's something I want to evaluate changing in the future.

**Comment by Lange** [comment]
This should be fixed now! Go ahead and pull down the latest commit to `master` and give it a shot.
