### ISSUE TITLE
Editing `nodecg` stanza in package.json sometimes causes all panels in that bundle to disappear

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#326]
Repro steps that I've used. There may be other equivalent repro steps:

1. Start NodeCG
2. Delete a panel from the `nodecg.dashboardPanels` stanza in `package.json`
3. Refresh the dashboard. There is a chance that all panels from that bundle will have disappeared until NodeCG is restarted.

**Comment by tprovick** [comment]
Changing the width also seems to trigger this.

1. Start NodeCG
2. Open dashboard
3. Change the width of a panel in the nodecg.dashboardPanels stanza in package.json
4. Refresh the dashboard. For me, 100% of the time all panels from that bundle will have disappeared until NodeCG is restarted.

I'm trying to finish my todo list early today so that I can try to look at this bug.

**Comment by Lange** [comment]
Fixed by abb1722.
